#!/bin/bash
#set -x
# java start script version 1.0
APP_HOME=`readlink -f $0`
APP_HOME=`dirname $APP_HOME`/gui
MAINJAR=target/cplan-gui.jar

if test -n "$DEBUG"; then
    JPDA_TRANSPORT="dt_socket"
    JPDA_ADDRESS="3194"
    JAVA_OPTS="-Xdebug -Xrunjdwp:transport=$JPDA_TRANSPORT,address=$JPDA_ADDRESS,server=y,suspend=n "
fi

if test "$1" = "-m" ; then
    JAVA_OPTS="${JAVA_OPTS} -Xmx${2}m "
    shift 2
else
    JAVA_OPTS="${JAVA_OPTS} -Xmx768m "
fi

if test -f "log4j.properties" ; then
    L4JSETUP="log4j.properties"
else
    if test -f "${APP_HOME}/config/log4j.properties"; then
        L4JSETUP="${APP_HOME}/config/log4j.properties"
    fi
fi

if test -n "$L4JSETUP" ; then
    JAVA_OPTS="$JAVA_OPTS -Dlog4j.configuration=file:${L4JSETUP}"
fi
eval "java $JAVA_OPTS -Dapp.dir=\"$APP_HOME\" -jar \"$APP_HOME\"/$MAINJAR $opts $@"
