#!/bin/bash
#set -x
# java start script version 1.0

here="`pwd`"
cd "`dirname $0`"
APP_HOME="`pwd`"
#BINARY=true
if test -z "$BINARY" -a -d src ; then
    ant all > /dev/null 2>&1
fi
cd "$here"
export APP_HOME

if echo `uname` | grep -qi "cygwin" ; then
    CYGWIN=true
fi

if test -n "$DEBUG"; then
    JPDA_TRANSPORT="dt_socket"
    JPDA_ADDRESS="3194"
    JAVA_OPTS="-Xdebug -Xrunjdwp:transport=$JPDA_TRANSPORT,address=$JPDA_ADDRESS,server=y,suspend=n "
fi


if test -z "$CYGWIN" ; then
    if test -n "$JAVA_HOME" ; then
        "$JAVA_HOME"/bin/java -version 2>&1 | grep -q "version \"*1\.[56]" ||
        unset JAVA_HOME JAVA_BINDIR JAVA_ROOT JDK_HOME JRE_HOME
    fi
    CPSEP=':'
else
    CPSEP=';'
fi

# look for an appropriate java installation
{
IFS=$'\n'
if test -z "$CYGWIN" -a -z "$JAVA_HOME" ; then
    for path in `type -all java`; do
        JAVA_HOME=`echo "${path##java is}" | sed 's|.* \(/.*\)/bin/java|\1|'`
         if test -n "$JAVA_HOME" &&
            $JAVA_HOME/bin/java -version 2>&1 | grep -q "version \"*1\.[56]" ; then
            export JAVA_HOME
            break
        else
            unset JAVA_HOME
        fi
    done
fi
if test -z "$CYGWIN" -a "x$JAVA_HOME" = "x" ; then
    echo "No appropriate java installation found (at least version 1.5)"
    echo "... exiting"
    exit 1;
fi
}
if test "$1" = "-m" ; then
    JAVA_OPTS="${JAVA_OPTS}-Xmx${2}m "
    shift 2
else
    JAVA_OPTS="${JAVA_OPTS}-Xmx768m "
fi

dozify_path() {
    if test -n "$CYGWIN" ; then
        echo "$1" | \
            sed -e 's|/cygdrive/c|C:|g' -e 's|/cygdrive/d|D:|g' -e 's@/@\\@g'
    else
        echo "$1"
    fi
}

cygwinify_path() {
    if test -n "$CYGWIN" ; then
        here=`pwd`
        cd "$1"
        result=`pwd`
        cd "$here"
        echo $result
    else
        echo $1
    fi
}

JAVA_OPTS="${JAVA_OPTS}-cp `dozify_path "$APP_HOME/target/lib/java/\*"` "

if test -f "log4j.properties" ; then
    L4JSETUP="log4j.properties"
else
    if test -f "${APP_HOME}/config/log4j.properties"; then
        L4JSETUP="${APP_HOME}/config/log4j.properties"
    fi
fi

L4JSETUP=`dozify_path "$L4JSETUP"`

if test -z "$JAVA_HOME" ; then
    JAVA_BIN="java"
else
    # won't work, i'm sure
    JAVA_BIN=`cygwinify_path "$JAVA_HOME/bin/java"`
fi

APP_HOME=`dozify_path $APP_HOME`

if test -n "$L4JSETUP" ; then
    JAVA_OPTS="$JAVA_OPTS -Dlog4j.configuration=file:${L4JSETUP}"
fi
MAINCLASS=de.dfki.lt.tr.dialogue.cplan.InteractivePlanner
eval "$JAVA_BIN" "$JAVA_OPTS" $MAINCLASS -A "'$APP_HOME'" $* || echo "$usage"
